- name: 磁盘xfs分区以及自动挂载设置
  script: /root/gpushare-deploy/roles/agent/files/disk.sh "{{ DISK }}" "{{ MOUNT_PATH  }}"   
- name: 增加apt gpushare 专有apt源
  shell: echo "当前环境是在线环境，设置apt源为公网源" && sleep 3 && \
         mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
         echo "deb {{ PUBULIC_REPO }} debs/" >/etc/apt/sources.list
         
- name: 安装docker以及nvidia-docker2
  shell: export DEBIAN_FRONTEND=noninteractive && apt  update  --allow-insecure-repositories && apt install nvidia-docker2 -y
  ignore_errors: yes

- name: 分发渲染docker.service和daemon.json
  template: src={{ item.name }} dest={{ item.path }}
  with_items:
    - {name: 'daemon.json.j2', path: '/etc/docker/daemon.json'}
    - {name: 'docker.service.j2', path: '/lib/systemd/system/docker.service'}

- name: 删除旧的dockerd
  shell: rm -rf /usr/bin/dockerd

- name: "拷贝新版dockerd二进制文件"
  copy: src=dockerd dest=/usr/bin/dockerd mode=777   #后续和开发确认dockerd永远放在oss固定连接上。

- name: 使用systmectl daemon-reload加载新的service文件
  shell: "systemctl daemon-reload && service docker restart"

- name: 开机启动docker服务
  service: name=docker  state=started enabled=true


